### ISSUE TITLE
[BUG]API 仕様書とサーバ実装の乖離を直す

### ISSUE THREAD

**Issue by h-takeyeah** [su-its/typing#50]
こことか https://github.com/su-its/typing/blob/62dfc5d1701ce9705d644227a5c418f9e19a089d/typing-server/api/handler/score.go#L46

- `score.go`

**Comment by KinjiKawaguchi** [comment]
@KinjiKawaguchi 
- [ ] ボディーから情報を取得
- [ ] ポスト時に正しくスコアが登録されない
