### ISSUE TITLE
[FEATURE]ゲーム開始前の画面開発

### ISSUE THREAD

**Issue by Shibatch28** [su-its/typing#56]
## TODO
- レイアウトの確認
- 説明の内容に何を入れるか

**Comment by KinjiKawaguchi** [comment]
#57

**Comment by h-takeyeah** [comment]
何が説明として適切か考えるためにいくつかの例を見てみました。(まーこんなのを並べるよりスケッチの一つでも描いた方が叩きたいができて議論が進むと思いますけどｗ)
### [寿司打](https://sushida.net/play.html)
遊び方ボタンを押すと説明が出てきて、その他いろいろ説明が書かれています

### [Easyタイピング](http://typingx0.net/easy/)
設定項目が一覧表示されています。設定をいじらずともそのままSpaceを押して始められる作りになっています
