### ISSUE TITLE
[BUG]GAME カーソルが消えて入力できなくなることがある

### ISSUE THREAD

**Issue by h-takeyeah** [su-its/typing#62]
## 該当コミット
3dddebabc1898a49bb6b471d289856069f63665e
## 症状
画像だとすでに改行されてますが、もともと "keyboards." の右に "Peter Piper" が表示されてました。"keyboards." まで入力してスペースキーを押すと、画像のように"Peter Piper"が次の行に行き、その後キーを押しても反応しないという状況を観測しましたた。他の人再現しますか？

## スクリーンショット
![image](https://github.com/su-its/typing/assets/61489178/d2d7aa03-344b-409c-b65a-f2444280e825)

**Comment by h-takeyeah** [comment]
別のコミットですが、開発者ツールを開いてるときに観測したので共有します
![image](https://github.com/su-its/typing/assets/61489178/2b00c3d3-a7c0-4190-b688-a99a8691c7be)

**Comment by KinjiKawaguchi** [comment]
テキストに改行があると、起こります。
