### ISSUE TITLE
[FEATURE]入力速度のグラフを調整

### ISSUE THREAD

**Issue by KinjiKawaguchi** [su-its/typing#78]
- [x] 対数関数とか
- [ ] 平均のグラフってちゃんと動いてた？

**Comment by h-takeyeah** [comment]
> 対数関数とか

に関しては #120 の 3efbee272061e0af6fc3290001491f636ff766ad にて線形のものに置き換えられた。理由は「200～300あたりを上限にした方が激しく動いて良いんじゃない？」に実装者およびチームリーダーが賛成したため。
